### ISSUE TITLE
imdb lookup

### ISSUE THREAD

**Issue by rlemon** [Zirak/SO-ChatBot#189]
imdb has a undocumented api. Zirak is bauce so he can figure it out no problem. 

link to relevant SO issue:  
http://stackoverflow.com/questions/1966503/does-imdb-provide-an-api/7744369#7744369  

get on it!

**Comment by Zirak** [comment]
This seems to have been done in 248d44bb17869cda88f9983885994ef847bb724c. I didn't even notice.

**Comment by rlemon** [comment]
my bad, I should have closed this.

**Comment by shea-sollars** [comment]
seemed relevant, thought I'd leave this here: https://www.themoviedb.org/documentation/api
it's an imdb alternative, and it's decent
