### ISSUE TITLE
undo should be localized to the room

### ISSUE THREAD

**Issue by AmaanC** [Zirak/SO-ChatBot#195]
Running the command in a particular room should delete the last message by her in that particular room.

Example of a [message](http://chat.stackoverflow.com/messages/15667627/history) being undone from a [message in another room](http://chat.stackoverflow.com/transcript/message/15667629#15667629)

**Comment by rlemon** [comment]
this was fixed.. idk when. but it was fixed.

**Comment by Zirak** [comment]
Really? How?

**Comment by rlemon** [comment]
not sure, but I tested in C# and sandbox and !!undo works fine in the respective room it was called from.
