### ISSUE TITLE
Lack of Flak Jacket for Backtrack Attack

### ISSUE THREAD

**Issue by kendfrey** [Zirak/SO-ChatBot#217]
...aka catastrophic regex injection.

Example attack:

`!!s/(((.*|.*)*|(.*|.*)*)*|((.*|.*)*|(.*|.*)*)*)*(?!)//`

This regex will match nothing and take a very long time in doing so.

Such regexes can also be passed to `!!learn` to create 'forkbomb' commands.

Suggested solution: Run regexes the same way as `!!>` JavaScript, with an appropriate timeout.

If a `!!s` times out, it should abort the entire command and not continue looking for matches.

**Comment by Zirak** [comment]
Got closed by 4073be44cde9b333c6f46fdebf940b05baf02a1b, forgot all about it. Huzzah!
