### ISSUE TITLE
Wrong gif moving

### ISSUE THREAD

**Issue by cauburtin** [Zirak/SO-ChatBot#229]
The message I posted: http://chat.stackoverflow.com/messages/21935602/history

How the bot replaced it: http://chat.stackoverflow.com/messages/21935615/history

So wrong name and wrong moved message link

**Comment by Zirak** [comment]
Gif binning isn't part of the bot (yet, see #226), @rlemon just runs it on her (since he's hosting it in the js room).

So closing since it's not really about the bot.

**Comment by cauburtin** [comment]
ok
