### ISSUE TITLE
bring back !!roll

### ISSUE THREAD

**Issue by rlemon** [Zirak/SO-ChatBot#237]
sure it wasn't used so often, but it was very handy when it was needed. It didn't clutter things up, and it wasn't that susceptible for spam.  we should bring it back.

**Comment by elliotbonneville** [comment]
I concur, I was forced to invoke the JS eval command to get my diceroll. I want my money back!

**Comment by Shmiddty** [comment]
![Next issue!](https://imgs.xkcd.com/comics/random_number.png)

**Comment by rlemon** [comment]
nothing is happening here. seems it has been forgotten about.

**Comment by Zirak** [comment]
hrm, will it be used? I'm guessing nerds from the c# room (*cough* @kendfrey *cough*) might use it. It's also a matter of reverting a commit, so reintroducing it won't be a problem.
