### ISSUE TITLE
Is !!/norris command broken?

### ISSUE THREAD

**Issue by TheItachiUchiha** [Zirak/SO-ChatBot#239]
I tried the command "!!/norris" as documented [here](https://github.com/Zirak/SO-ChatBot/wiki/Commands#norris). But the bot doesn't throw back the expected reply.

For reference, http://chat.stackoverflow.com/transcript/message/23575783#23575783

Is the command broken? Or am I doing something wrong?

**Comment by Zirak** [comment]
Oh my, the documentation is outdated. `/norris` was deprecated some time back in 79ca4daa0c1f9aee861ea73a43cd9ccd364610bc.

Will fix documentation

**Comment by Zirak** [comment]
Updated.

https://github.com/Zirak/SO-ChatBot/wiki/Commands/_compare/6d179edf6fe74c922115cd89efbcfc4a96169082...bee36aa4cbf95e98c7193296849fbdd53ac52f04

**Comment by Zirak** [comment]
I'm dumb
