### ISSUE TITLE
Display XKCD alt-text when Feeds posts a new XKCD.

### ISSUE THREAD

**Issue by HorizonShadow** [Zirak/SO-ChatBot#241]
Title. 

I found myself being mildly inconvenienced when Feeds posted an XKCD and I had to load the page to view the alt-text. This has to be rectified.

**Comment by Zirak** [comment]
Feeds inserts the alt text as (surprise) alt text, hover over the image to see it.

**Comment by HorizonShadow** [comment]
Huh.
