### ISSUE TITLE
correcting a wrong command. 

### ISSUE THREAD

**Issue by rlemon** [Zirak/SO-ChatBot#247]
Sometimes we all do it, `!!some bullshit we didn't mean` and cap complains and then we edit the message and correct the command. I propose that she (if withing the time frame of course) edit the complaining message with the new results rather than leave it. 

I have thought about how this could be implemented and I don't think it would be too difficult ( can talk to you Zirak if you want a hand ). 

I think overall it will make for a smoother user experience. What does everyone think?

**Comment by CallumBarclay** [comment]
This sounds like a great idea, and it would cut down on the Caprica-spam, too.

**Comment by nmai** [comment]
+1

**Comment by onebree** [comment]
+1, such a great idea, it is a top shelf tacos idea

**Comment by Zirak** [comment]
Dup of https://github.com/Zirak/SO-ChatBot/issues/27 . It's not that difficult, but involves annoying book keeping.
