### ISSUE TITLE
!!weather city isn't working

### ISSUE THREAD

**Issue by rahul-desai3** [Zirak/SO-ChatBot#256]
The bot is returning `[object Event]` when tested in [StackOverflow Javascript chatroom](http://chat.stackoverflow.com/rooms/17/javascript).

**Comment by rlemon** [comment]
Maybe that is the local weather. ever think of that?

**Comment by rahul-desai3** [comment]
LOL
Anyway, I tried `!!weather Sunnyvale` and also `!!weather Pune`, both did not work.

**Comment by onebree** [comment]
Can confirm -- `!!weather 07701` is broken as well in the Ruby room.

http://chat.stackoverflow.com/transcript/message/27896365#27896365

**Comment by rlemon** [comment]
@Zirak this is broken again, as reported in #298   

so, umm, what did you change to fix it?

**Comment by rlemon** [comment]
fixed in commit c5e981a46cb7302ed8701b258265b5026eb98972
