### ISSUE TITLE
Please recommend output producing paste sites 

### ISSUE THREAD

**Issue by limeblack** [Zirak/SO-ChatBot#277]
Caprica Six responds with the following for unformatted code.

> @user Please don't post unformatted code - hit Ctrl+K before sending, use up-arrow to edit messages, and see the faq. For posting large code blocks, use a paste site like gist.github.com, hastebin.com or pastie.org

Could would please add one of the following sites to the list
https://jsfiddle.net/ http://codepen.io/pen/ https://jsbin.com

**Comment by rlemon** [comment]
Those are demo sites, not paste sites. They serve a similar but different purpose. I think if we are to amend the message and add those we should note that. 

> For posting large code blocks, use a paste site like gist.github.com, hastebin.com or pastie.org, Or if you have a complete demo consider using .....

**Comment by Zirak** [comment]
Thanks! The new message is:

> Please don't post unformatted code - hit Ctrl+K before sending, use up-arrow to edit messages, and see the [faq](/faq). For posting large code blocks, use a paste site like https://gist.github.com, http://hastebin.com, http://pastie.org or a demo site like https://jsbin.com/
