### ISSUE TITLE
!!afk, (afk+comma) turns command into a weasel response. 

### ISSUE THREAD

**Issue by rlemon** [Zirak/SO-ChatBot#278]
![](http://i.imgur.com/lpgOo9L.png)  

I noticed this when Benji went afk with a comma and the bot responded with 'no'.

It isn't a command as far as I can tell ( no one fucking with me ).

**Comment by Zirak** [comment]
Commas are valid in command names (I think any non-space character is) so the bot tried to find an `afk,` (notice the comma) command. Failing to find any, it went on to match listeners, and the weasel happily matched `am I beautiful`.

The following would also match:

> !!listcommands, am I beautiful?
