### ISSUE TITLE
!!meow command shows two gifs

### ISSUE THREAD

**Issue by EvelinFoxell** [Zirak/SO-ChatBot#282]
When you use the `!!meow` command one gif loads but is replaced by another one.

Also, not sure if intended, but she shows a different gif for every user.

**Comment by rlemon** [comment]
` User-taught command:  <>http://thecatapi.com/api/images/get?format=src&type=gif&random=$rand(1,100000‌​0)#.gif`

this command hits an external api which delivers the image. It is user taught and not part of the core bot.
