### ISSUE TITLE
remove !!die

### ISSUE THREAD

**Issue by rlemon** [Zirak/SO-ChatBot#284]
it is used to shut down the bot for 'kicks' from some people. I understand the original intent behind it being a safety net, but so far I don't think it has ever been used that way. 

Alternatively lock it down to owners only.

**Comment by allquixotic** [comment]
Good idea. This has (very occasionally) been a problem in Root Access, too, so we're happy to see this be locked down to room owners (since we've definitely enough active room owners to handle a runaway bot if necessary).

**Comment by Zirak** [comment]
Looks like 2167e0788b92cc6f0588699b29cb84e9f0410f3e dealt with it, so justice for all!
Thanks @rlemon.
