### ISSUE TITLE
Cap dead in Android Era with Kotlin and Java

### ISSUE THREAD

**Issue by limeblack** [Zirak/SO-ChatBot#288]
Cap is dead in https://chat.stackoverflow.com/rooms/19132/android-era-with-kotlin-and-java

Cap doesn't respond to commands.

**Comment by tejasacquaintsoft** [comment]
May be because of hansmaster

**Comment by tcaterinchater** [comment]
May be because of some master.

**Comment by Zirak** [comment]
Seems fine now, have fun.
