### ISSUE TITLE
Question for Zirak: Can I make a bot based on yours?

### ISSUE THREAD

**Issue by TheOneWhoMade** [Zirak/SO-ChatBot#294]
Recently I have made a bot with your framework. [You can see him here](https://github.com/TheOneWhoMade/Node-NN-chatbot). What I am wondering is should bugs relating to the commands be redirected to this repo? Also, I want you to know that the bot I am making will eventually be an AI...

**Comment by Zirak** [comment]
The bot is licensed under the [WTFPL](http://www.wtfpl.net/), which means you are free to do with it as you please, no strings attached. Bug reports are of course welcome, and of course any contributions to upstream would also be welcome.

Good luck in your project.
