### ISSUE TITLE
[BUG] Weather command

### ISSUE THREAD

**Issue by Sneezor** [Zirak/SO-ChatBot#298]
The /weather command returns [object Event].

Example.
Input: !!weather spain
Expected output: 15ºC (Or any temperature according to weather service).
Output: [object Event]

**Comment by rlemon** [comment]
this was already reported https://github.com/Zirak/SO-ChatBot/issues/256 

I'll reopen that issue and see why the fix didn't stick.

**Comment by rlemon** [comment]
fixed in commit c5e981a46cb7302ed8701b258265b5026eb98972
