### ISSUE TITLE
afk command broken

### ISSUE THREAD

**Issue by Regenhardt** [Zirak/SO-ChatBot#304]
`afk` command doesn't seem to work. Small excerpt:

![afk](https://user-images.githubusercontent.com/10476293/41601728-7679f858-73d9-11e8-8ffb-3c30fb672b8c.png)

**Comment by AmaanC** [comment]
IIRC, there's about a one minute window before your afk-ness actually kicks
in. Try not talking for a over a minute after running the command and then
having someone ping you.

If it isn't already, this should probably be documented in the help for the
command if it exists too.

**Comment by kendfrey** [comment]
[It's a feature, not a bug.](../blob/master/source/plugins/afk.js#L19)

**Comment by rlemon** [comment]
two minutes.
