### ISSUE TITLE
!!free Wietlol

### ISSUE THREAD

**Issue by wietlol** [Zirak/SO-ChatBot#305]
User Wietlol has been put in mindjail on 20th of April.
I think it has been long enough.

The reason was for `!!forget forget` which got me instantly banned.

however, the same has been done by
Neoares, Jan Dvorak, monners, Abhishek Hingnikar, Mosho, SomeKittens, Darkyen and even a `!!sudo forget forget` by Ale and SomeKittens
Yet none of them got banned for it either.

Since ssube was the one that banned me, and Kendall, rlemon and Zirak wants no part in this mess, it is up to @ssube to unban Wietlol.

**Comment by rlemon** [comment]
This is not an issue that belongs here, it was my mistake for directing you to github without providing links. Open this on the [appropriate repo](https://github.com/JavaScriptRoom/culture) and we can use ssubes comment here to allow RO's to decide if you should be unbanned.
