### ISSUE TITLE
Let's bet on it!

### ISSUE THREAD

**Issue by ralt** [Zirak/SO-ChatBot#82]
New command proposal: `!!bet`

Usage:

    @FlorianMargaine: !!bet new 60 Will jAndy rep whore on this question?
    @Bot: New bet registered. ID: 123456. Use `!!bet 123456 yes 1000` or `!!bet 123456 no 1000` to bet 1000 internet points.

Everybody starts up with 100 internet points.

Of course, when the fact is decided, someone has to finish the bet by saying:

    !!bet decided 123456 yes

And the internet points will be given/taken according to the bet's ratio.

Format:

    bet new <minutes> <question>
    bet <id> <yes/no> <internet points>
    bet decided <id> <yes/no>

Sounds like to me it could be lot of fun, especially since bets could be on anything. (It should be related to SO though.)

Some examples:

- Will Benjamin get more than 10 upvotes on his last answer?
- Will Zirak write a funny answer?
- Will rlemon get 10k rep before 2023?

**Comment by Zirak** [comment]
Closing for about the same reasons as #231, comment if you want this.
